### ISSUE TITLE
Fix dependency for sublime-text-3200

### ISSUE THREAD

**Issue by jorgicio** [DamnWidget/sublime-text#37]
Hi!

Thanks for the sublime-text-3200 package. However, GTK+ 2 support was dropped and uses GTK+3 instead.

Greetings!

**Comment by o0Ignition0o** [comment]
Hi :) Oh I haven't noticed that at all! I m unfortunately not comfortable enough with gentoo and ebuilds yet to figure out what would be the best way to procees (wrt ebuild file name, and the update mechanism)

I can submit a patch if anyone is willing to tell me which way is recommended (maybe bumping the ebuild version would be better because it would allow people to update?)

**Comment by jorgicio** [comment]
Just do an -r1 version and replace the :2 for :3 in the gtk dependency variable.

**Comment by o0Ignition0o** [comment]
`>=x11-libs/gtk+-2.24.8-r1:3`
Thanks for the help :)

**Comment by jorgicio** [comment]
No problem, but I would replace the "2.24.8" by just "3.0", because the 2.2x.x is for the 2 branch and not the the 3.

Anyways, thank you.

**Comment by o0Ignition0o** [comment]
Ok, editing it now :)

**Comment by OtaK** [comment]
I'd just go with `x11-libs/gtk+:3`, as it'd select whatever version is existing in slot 3.

**Comment by o0Ignition0o** [comment]
Ok I think it should be it.
